### PR TITLE
Track Julia 0.4 syntax

### PR DESCRIPTION
**Pull request by garborg**

### CODE REVIEW

**Comment by IainNZ** [comment]
@garborg would you be comfortable having write access for JuliaWeb?

**Comment by garborg** [comment]
I would. I'm a little crunched for time these days, too, but I'll certainly help out when I can.

**Comment by IainNZ** [comment]
You should be able to merge when ready

**Comment by garborg** [comment]
No merge button on refresh or email about JuliaWeb quite yet.

**Comment by IainNZ** [comment]
Woops!

**Comment by garborg** [comment]
Got it!

**Pull request merged**
