### PR TITLE
Update deprecations

### PR DESCRIPTION
**Pull request by musm**
Please just squash before merging.

### CODE REVIEW

**Comment by musm** [comment]
https://github.com/JuliaWeb/URIParser.jl/pull/48 closes

**Comment by musm** [comment]
also can we tag after this merges?

**Comment by quinnj** [comment]
Looks good, thanks!

**Comment by musm** [comment]
Thanks. 

https://github.com/attobot/attobot   should make tagging and the push to metadata a pinch if it's not already installed.

**Pull request merged**
